#!/bin/sh

interface="${interface}"
inet="${inet}"
ip=$(ip address show $interface | grep $inet | awk '{print $2}' | cut -d/ -f1 | head -n 1)

echo "" $ip # full text
echo $ip # short text
echo "#00FF00"

